server:
  port: 18084

spring:
  # 非web应用
  main:
    web-application-type: none
  application:
    name: demo-monitor-core
  cloud:
    nacos:
      discovery:
        enabled: true
        ip: ${host.inner}
        server-addr: ${nacos.cluster}
        group: DEFAULT_GROUP
      config:
        server-addr: ${nacos.cluster}
        group: DEFAULT_GROUP
  #        import-check:
  #          enabled: false
  config:
    import:
      - nacos:monitor-core-prod.yml?group=DEFAULT_GROUP

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.hy.project.demo.monitor.core.mybatis.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

# actuator 监控配置
management:
  #actuator端口 如果不配置做默认使用上面8080端口
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        #默认值访问health,info端点  用*可以包含全部端点
        include: "health,metrics"
      #修改访问路径 2.0之前默认是/; 2.0默认是/actuator可以通过这个属性值修改
      base-path: /actuator
    jmx:
      exposure:
        exclude: "*" #jmx不公开所有端点
  endpoint:
    shutdown:
      enabled: true #打开shutdown端点
    health:
      show-details: always #获得健康检查中所有指标的详细信息

# ES 相关
es:
  cert:
    filePath: /var/ca.crt
  user:
    name: elastic
    pwdPath: /var/pwd_elastic

dubbo:
  application:
    name: demo-monitor-core
    logger: slf4j
  protocol:
    name: dubbo
    port: -1
    accesslog: true
  provider:
    filter: providerTraceIdFilter,default,providerLogFilter,providerExceptionHandleFilter
  registry:
    protocol: nacos
    address: ${nacos.cluster}
    parameters:
      namespace: public
      group: DUBBO_GROUP
  config-center:
    protocol: nacos
    address: ${nacos.cluster}
    group: DUBBO_GROUP
  metadata-report:
    protocol: nacos
    address: ${nacos.cluster}
    group: DUBBO_GROUP

kafka:
  bootstrap-servers: ${kafka.bootstrap.servers}