server:
  port: 8080
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.61.11:3306/default?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${mysql.user}
    password: ${mysql.pwd}

  #前端文件目录
  resources:
    static-locations: file:/var/front/

  #redis
  redis:
    host: 47.99.61.11
    port: 6379
    #Redis数据库索引（默认为0）
    database: 0
    #超时时间，毫秒
    timeout: 5000

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.hy.project.demo.mybatis.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

# actuator 监控配置
management:
  #actuator端口 如果不配置做默认使用上面8080端口
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        #默认值访问health,info端点  用*可以包含全部端点
        include: "health,metrics"
      #修改访问路径 2.0之前默认是/; 2.0默认是/actuator可以通过这个属性值修改
      base-path: /actuator
    jmx:
      exposure:
        exclude: "*" #jmx不公开所有端点
  endpoint:
    shutdown:
      enabled: true #打开shutdown端点
    health:
      show-details: always #获得健康检查中所有指标的详细信息
