example:
  name: RICK
  age: 11
  
auth:
  maps:
    # :::::::::::::: UserController ::::::::::::::
    "/user/me.json": SUPER_ADMIN,LOGIN_NORMAL

    "/user/list.json": SUPER_ADMIN,USER_QUERY,USER_MANAGE
    "/user/getById.json": SUPER_ADMIN,USER_QUERY,USER_MANAGE

    "/user/update.json": SUPER_ADMIN,USER_MANAGE
    "/user/deleteById.json": SUPER_ADMIN,USER_MANAGE
    "/user/updatePwd.json": SUPER_ADMIN,USER_MANAGE
    "/user/updateUserRoles.json": SUPER_ADMIN,USER_MANAGE

    # :::::::::::::: AuthController ::::::::::::::
    "/auth/permission/list.json": SUPER_ADMIN,PERMISSION_QUERY,PERMISSION_MANAGE

    "/auth/permission/create.json": SUPER_ADMIN,PERMISSION_MANAGE
    "/auth/permission/deleteById.json": SUPER_ADMIN,PERMISSION_MANAGE

    "/auth/role/list.json": SUPER_ADMIN,ROLE_QUERY,ROLE_MANAGE
    "/auth/role/create.json": SUPER_ADMIN,ROLE_MANAGE
    "/auth/role/deleteById.json": SUPER_ADMIN,ROLE_MANAGE
    "/auth/role/updateRolePermissions.json": SUPER_ADMIN,ROLE_MANAGE