server:
  port: 18082

spring:
  # 非web应用
  main:
    web-application-type: none
  application:
    name: demo-auth-core
  cloud:
    nacos:
      discovery:
        enabled: true
        ip: 203.119.160.26
        server-addr: 139.224.72.37:8848,106.14.208.194:8848,139.196.230.113:8848
        group: DEFAULT_GROUP
      config:
        server-addr: 139.224.72.37:8848,106.14.208.194:8848,139.196.230.113:8848
        group: DEFAULT_GROUP
#        import-check:
#          enabled: false
  config:
    import:
      - nacos:auth-core-prod.yml?group=DEFAULT_GROUP

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.hy.project.demo.auth.core.mybatis.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    #sql日志，dev调试用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 单点登录配置
sso:
  token:
    header: Authorization
    # 失效时间（分钟）
    expireTime: 30
    # 每次处理的最大token个数
    maxExpireCount: 100
  user:
    # 失效时间（分钟）(24小时）
    expireTime: 1440

dubbo:
  application:
    name: demo-auth-core
    logger: slf4j
  protocol:
    name: dubbo
    port: -1
    accesslog: true
  provider:
    filter: providerTraceIdFilter,default,providerLogFilter,providerExceptionHandleFilter
  registry:
    protocol: nacos
    address: 139.224.72.37:8848,106.14.208.194:8848,139.196.230.113:8848
    parameters:
      namespace: public
      group: DUBBO_GROUP
  config-center:
    protocol: nacos
    address: 139.224.72.37:8848,106.14.208.194:8848,139.196.230.113:8848
    group: DUBBO_GROUP
  metadata-report:
    protocol: nacos
    address: 139.224.72.37:8848,106.14.208.194:8848,139.196.230.113:8848
    group: DUBBO_GROUP