server:
  port: 18080

spring:
  application:
    name: demo-web
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: false
        ip: 172.27.183.154
        server-addr: 172.27.183.154:8848,172.27.183.155:8848,172.27.183.156:8848
        group: DEFAULT_GROUP

#feign:
#  httpclient:
#    enabled: true # 支持httpClient 默认为true
#    max-connections: 200 #最大连接数
#    max-connections-per-route: 50 # 单个路径的最大连接数
#  circuitbreaker:
#    enabled: true

# 单点登录配置
sso:
  token:
    header: Authorization
    # 失效时间（分钟）
    expireTime: 30
    # 每次处理的最大token个数
    maxExpireCount: 100
  user:
    # 失效时间（分钟）(24小时）
    expireTime: 1440

dubbo:
  application:
    name: demo-web
  consumer:
    timeout: 60000
    retries: 0
    filter: consumerTraceIdFilter,default,consumerLogFilter
  protocol:
    name: dubbo
    port: -1
  registry:
    protocol: nacos
    address: 139.224.72.37:8848,106.14.208.194:8848,139.196.230.113:8848
    parameters:
      namespace: public
      group: DUBBO_GROUP
  config-center:
    protocol: nacos
    address: 139.224.72.37:8848,106.14.208.194:8848,139.196.230.113:8848
    group: DUBBO_GROUP
  metadata-report:
    protocol: nacos
    address: 139.224.72.37:8848,106.14.208.194:8848,139.196.230.113:8848
    group: DUBBO_GROUP
