server:
  port: 18080

spring:
  application:
    name: demo-web
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: false
        ip: ${host.inner}
        server-addr: ${nacos.cluster}
        group: DEFAULT_GROUP
      config:
        server-addr: ${nacos.cluster}
        group: DEFAULT_GROUP

  config:
    import:
      - nacos:web-prod.yml?group=DEFAULT_GROUP

#feign:
#  httpclient:
#    enabled: true # 支持httpClient 默认为true
#    max-connections: 200 #最大连接数
#    max-connections-per-route: 50 # 单个路径的最大连接数
#  circuitbreaker:
#    enabled: true

# 单点登录配置
sso:
  token:
    header: Authorization
    # 失效时间（分钟）
    expireTime: 30
    # 每次处理的最大token个数
    maxExpireCount: 100
  user:
    # 失效时间（分钟）(24小时）
    expireTime: 1440

dubbo:
  application:
    name: demo-web
  consumer:
    timeout: 60000
    retries: 0
    filter: consumerTraceIdFilter,default,consumerLogFilter
  protocol:
    name: dubbo
    # 从20880开始自动寻找可用的端口
    port: -1
  registry:
    protocol: nacos
    address: ${nacos.cluster}
    parameters:
      namespace: public
      group: DUBBO_GROUP
  config-center:
    protocol: nacos
    address: ${nacos.cluster}
    group: DUBBO_GROUP
  metadata-report:
    protocol: nacos
    address: ${nacos.cluster}
    group: DUBBO_GROUP
